name: main
on:
  push:
    branches:
      - 'releases/**'


jobs:
  nodejs:
    if: ${{ contains(github.event.repository.name, 'maven') }}
    uses: bescribanobegue/maven-test-workflow/.github/workflows/springboot-ci.yaml@main
    secrets: inherit
