name: main
on:
  push:
    branches: 
    # - main
    - 'feature/**'
  pull_request:
    types: [opened, reopened, edited, auto_merge_enabled]

jobs:
  nodejs:
    if: ${{ contains(github.event.repository.name, 'maven') }}
    uses: bescribanobegue/test-maven/.github/workflows/springboot-ci.yaml@feature/test
    secrets: inherit
