name: springboot-ci
on:
  workflow_call:
  repository_dispatch:
    types: [backend]
jobs:
  springboot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'https://sonarcloud.io/'
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bescribanobegue_${{ github.event.repository.name }} -Dsonar.organization=bescribanobegue -Dsonar.host.url=${{ env.SONAR_HOST_URL }} -Dsonar.qualitygate.wait=true

      # - name: Build
      #   run: mvn compile -DskipTests
      # - name: Test
      #   run: mvn test
      # - name: Package
      #   run: mvn package -DskipTests


      # - name: Login to Artifactory
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.ARTIFACTORY_USERNAME }}
      #     password: ${{ secrets.ARTIFACTORY_TOKEN }}
      #     registry: ${{ env.ARTIFACTORY_REGISTRY }}
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: ${{ env.REPOSITORY }}/:${{ env.VERSION }}
      # - name: Deploy with Helm
      #   if: ${{ env.IS_LIBRARY == true }}
      #   run: helm upgrade --install ${env.APP_NAME} manifests/helm/charts/microservice --values ${env.PROJECT_KEY}/values.yaml -n ${env.PROJECT_KEY} --create-namespace